### ISSUE TITLE
How to stop the animation?

### ISSUE THREAD

**Issue by xico42** [bfeher/BFRadialWaveView#1]
I notice that when i leave the screen, and then comeback, the radialView is stopped. That's why in
the examples in the view: willAppear lifecycle method it is used [radialView show];

But i would like to stop the animation at a certain point. How could i achieve it?

**Comment by bfeher** [comment]
Hi fco-edno!

The animation is just a loop repeating forever that animates the .strokeEnd of each circle from 0 to 0.5. If you want to stop the animation at a specific point, you will need to remove the animation and then set the .strokeEnd of each circle to the desired value between 0 and 1.

I found [this link on SO describing how to pause and resume a CABasicAnimation](http://stackoverflow.com/questions/2306870/is-there-a-way-to-pause-a-cabasicanimation), but haven't been able to get it working. Perhaps you could give it a shot and submit a pull request if you get it working :)

**Comment by xico42** [comment]
Got it working, how do i submit a pull request? Also, you may adjust the storyboard, Still do not know
about size classes and constraints ;), this way the button i added in the storyboard is not well placed.

**Comment by xico42** [comment]
Just one more question, the number of topcircleLayers is the same of the bottomcircleLayers? I mean, always. The solution was simply iterate over the bottom and top circle layers, and do the way was done in that answer on SO. If the number of elements in the array would be always the same, i could make it with one for loop. The way i did it now, i did with two for loops.

**Comment by xico42** [comment]
Figured it out, i have just sent you a pull request, only with the pauseAnimation and resumeAnimation
methods included. Without including anything in the example storyboard and using two for loops.

**Comment by bfeher** [comment]
Hi fco-edno!
Thanks a lot for your help with this! Yes in fact bottom and top _should_ always be equal, and I don't really every check or enforce them to be the same, I always assume (which is unsafe...). 
So two loops is fine, thanks :)

I'll take a look at your pull request in a few minutes. Thanks again!
